### ISSUE TITLE
Add flesh block

### ISSUE THREAD

**Issue by MainGameCentral** [Jiingy/Jineric-Mod#11]
Add a flesh block crafted from 9 rotten flesh used to compact rotton flesh.

**Comment by Jiingy** [comment]
Flesh block has been added and is craftable. 

Still needs proper texture

**Comment by Jiingy** [comment]
Gonna go ahead and just call this one done even though the texture isn't final. Should be fairly obvious to remember to improve the texture. Otherwise, all functionality has been added.
