### ISSUE TITLE
Crash upon start up

### ISSUE THREAD

**Issue by IkolaNatari** [Jiingy/Jineric-Mod#116]
Hi here is a crash report, its possible that its just incompatible with one of the mods but I can't tell 
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-06-11 10:07:13
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'jineric'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: jineric:betterarcheology:rotten_wood_chest
	at net.minecraft.class_2960.method_45137(class_2960.java:252)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at jingy.jineric.registry.JinericEntityModelLayers.create(JinericEntityModelLayers.java:35)
	at jingy.jineric.registry.JinericEntityModelLayers.createChest(JinericEntityModelLayers.java:39)
	at jingy.jineric.registry.JinericEntityModels.lambda$register$1(JinericEntityModels.java:24)
	at it.unimi.dsi.fastutil.objects.ObjectArraySet$Spliterator.forEachRemaining(ObjectArraySet.java:294)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at jingy.jineric.registry.JinericEntityModels.register(JinericEntityModels.java:24)
	at jingy.jineric.base.JinericClientMain.onInitializeClient(JinericClientMain.java:28)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)

-- Initialization --
Corporation

	Fabric Mods: 
		abverticaledition: Additional Blocks: Vertical Edition 1.0.3
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20
		architectury: Architectury 9.0.7
		autohud: Auto HUD 5.0.3+1.20
			yaclx: YetAnotherConfigLibExtensions 1.2+1.20
		bambooeverything: Bamboo Everything 3.0.0-build.54+mc1.20
		bebooks: Better Enchanted Books 1.4.3
		betteranimationscollection: Better Animations Collection 7.0.0
		betterarcheology: Better Archeology 1.0.0
		bettercrafting: Craft Better 1.20-14
		biolith: Biolith 1.0.0-alpha.4
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.5
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.0-beta.1
		cherish: Cherish 1.2.0
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.3.2
		collective: Collective 6.57
		copperhopper: Copper Hopper 0.3.0+1.20.0
		diagonalfences: Diagonal Fences 7.0.0
		dungeons_andtaverns_mr: Dungeons and Taverns 1-v2.1.2
		earthtojavamobs: Earth2Java 1.10.1
		enchantmentsplus: Enchantments Plus 1.1.7+1.20
		fabric-api: Fabric API 0.83.0+1.20
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c927
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b27
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d127
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b27
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b27
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f27
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b27
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b327
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b327
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b27
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b27
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe27
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.10+b3afc78b27
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b27
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b27
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b27
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b327
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a27
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b27
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b27
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b327
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b27
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c627
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b27
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b27
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b27
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b27
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b327
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b27
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b27
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b27
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b27
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b327
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b327
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b27
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.4+b3afc78b27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b27
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b27
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b27
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b27
		fabricloader: Fabric Loader 0.14.21
		fallingtree: FallingTree 4.0.0
		fishingrework: Fishing Aquatica 1.20-0.2.6.1
		forgeconfigapiport: Forge Config API Port 7.0.0
		fwaystones: Fabric Waystones 3.1.2+mc1.20
		geckolib: Geckolib 4.2
			com_eliotlash_mclib_mclib: mclib 20
		globalpacks: Global Data- & Resourcepacks 1.16.1_fabric
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		guardvillagers: Guard Villagers Fabric 1.20-1.2.0
		handcrafted: Handcrafted 2.3.0
		indium: Indium 1.0.18+mc1.20
		inventorysorter: Inventory Sorter 1.8.10-1.20
			kyrptconfig: Kyrpt Config 1.5.3-1.20
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jineric: Jineric Mod b6.0.0+1.20
			mm: Manningham Mills 2.3
		lapisreserve: Lapis Reserve 1.0.8
		magnumtorch: Magnum Torch 7.0.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwpaintings: Macaw's Paintings 1.0.0
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20
		moblassos: Mob Lassos 7.0.0
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
			extensibleenums: Extensible Enums 7.0.0
		modmenu: Mod Menu 7.0.1
		morebows: More Bows Restrung 1.0.11+1.20.x
		moremobvariants: More Mob Variants 1.2.1
		nicer-skies: Nicer Skies 1.2.0
		noexpensive: NoExpensive 1.20-1.6.1
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		perfectplushies: Perfect Plushies 1.0.1
		placeableblazerods: Placeable Blaze Rods 3.0
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		puzzleslib: Puzzles Lib 7.0.2
		resourcefullib: Resourceful Lib 2.0.7
			com_teamresourceful_yabn: yabn 1.0.3
		ridehud: Ride Hud 1.2.3+1.20
		roughlyenoughitems: Roughly Enough Items 12.0.622
			error_notifier: Error Notifier 1.0.9
		saplanting: Saplanting 1.2.4
		seasons: Fabric Seasons 2.2.1+1.20
		sleepwarp: SleepWarp 2.1.0+1.20
		snowundertrees: Snow Under Trees 1.1.0+1.20
		sodium: Sodium 0.4.10+build.27
		taxfreelevels: Tax Free Levels 1.3.3
		terrablender: TerraBlender 3.0.0.163
		trimeffects: Trim Effects 1.0.1-fabric
		vanillaconfig: Vanilla Config 1.2.7+1.20
		vorpal-enchantment: Vorpal Enchantment 3.0.3
		xaerominimap: Xaero's Minimap 23.4.4
		xaeroworldmap: Xaero's World Map 1.30.3
	Launched Version: fabric-loader-0.14.21-1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Harrietmarie** [comment]
Yeah, I got this same error, except instead of the rotten wood chest I got the error for the baobab chest.

**Comment by lumiscosity** [comment]
same error with the blighted balsa chest. after some testing, these are the mods i found to cause this error:
- biome makeover
- hellion's sniffer+
- pearfection
edit: architectury and rei are actually fine

**Comment by Harrietmarie** [comment]
> same error with the blighted balsa chest. after some testing, these are the mods i found to cause this error:
> 
> * biome makeover
> * hellion's sniffer+
> * pearfection
> * architectury (the API used for REI among other mods)

To add to your list, Wilder Wild also generates this error

**Comment by Jiingy** [comment]
Will look into this ASAP. Can you provide the exact versions of the mods used along side Jineric Mod?

**Comment by Jiingy** [comment]
Found the issue, I add my own ChestEntityModelLayers by cycling through all the different WoodTypes of the game. With these mods adding to the list of WoodTypes, it creates a crash.

Will be working on a fix soon 👍
![image](https://github.com/Jiingy/Jineric-Mod/assets/69827559/540e398c-6dc9-43c4-9050-f9087bcac74f)

**Comment by Jiingy** [comment]
This issue is resolved in b6.0.1, please update the mod to get the fix!
https://modrinth.com/mod/jineric-mod/version/b6.0.1+1.20

**Comment by IkolaNatari** [comment]
Thank you so much, cant wait to use it!
