### ISSUE TITLE
Tumbleweed is missing block data and assets / Not fully implimented

### ISSUE THREAD

**Issue by lumiscosity** [Jiingy/Jineric-Mod#130]
The tumbleweed block has no name, and appears as block.jineric.tumbleweed.

![image](https://github.com/Jiingy/Jineric-Mod/assets/26834471/45419101-e6fb-4c44-80e9-89bf6672a627)

**Comment by Jiingy** [comment]
Tumbleweed is an unsupported/unfinished feature, so it's missing a lot of functionality. Will either be removing it, or trying to finish it when I can.

**Comment by Jiingy** [comment]
Removed tumbleweed, may implement later
