### ISSUE TITLE
players cannot connect online due to jineric mod 1.20.1

### ISSUE THREAD

**Issue by teshich** [Jiingy/Jineric-Mod#132]
![Знімок екрана 2023-12-16 192311](https://github.com/Jiingy/Jineric-Mod/assets/125819901/f0871a1d-7b7f-4229-9a95-bdc59804cedc)

**Comment by teshich** [comment]
was fixed after removing jineric mod

**Comment by Jiingy** [comment]
Please provide the **exact** version of the mod used (This would look something like "b.[mod version]+[mc version]". This is/was an issue with me modifying the recipe book category enum improperly on the server side at one point, which I had fixed in a certain version.

**Comment by Jediico** [comment]
Having this issue with "fabric 0.15.11" using "[beta] [backport] Jineric Mod b6.3.1+1.20.1"

**Comment by Jiingy** [comment]
Closing for being outdated, updating to 1.21.3
