### ISSUE TITLE
Wood chest varients

### ISSUE THREAD

**Issue by Jiingy** [Jiingy/Jineric-Mod#15]
- [x] Oak

- [x] Birch

- [x] Spruce

- [x] Jungle

- [x] Acacia

- [x] Dark Oak 

- [x] Warped Wood

- [x] Crimson Wood

**Comment by MrCheeze446** [comment]
expand this issue to cover anything that uses wood (or mostly everything)

**Comment by Jiingy** [comment]
Took a lot of work and time, but I did it. Oak chest needs to be either added on it's own or added over the regular chest still, but all chests are added including boreal (no textures yet)

![2022-05-01_21 15 27](https://user-images.githubusercontent.com/69827559/166626409-b5d3635a-9016-4c9d-8356-4d9a73ff9385.png)
