### ISSUE TITLE
Add shulker chest

### ISSUE THREAD

**Issue by MainGameCentral** [Jiingy/Jineric-Mod#29]
Block Features:
- Would function as a new late game storage alternative to shulker boxes.
- Crafted with one chest, and two shulker boxes. (Shulker box crafting recipe but on it's side)

Advantages:
- More storage than default chest.
- Solves problems of late game storage.

Disadvantages:
- It's crafting with a late game item.
- Not portable like a shulker box.

**Comment by Pizzachu22** [comment]
what exactly will this do

**Comment by MainGameCentral** [comment]
> what exactly will this do

no idea, Jingy just wanted me to add this so he doesnt forget

**Comment by Jiingy** [comment]
I'll explain later when I get on pc

**Comment by Jiingy** [comment]
[Post Updated]

**Comment by Jiingy** [comment]
Gonna give this one or two more goes and if I can’t get it working I’m going to shelve the idea for a later release. I've realized storage tile entities and tile entities are far out of my knowledge zone currently.

**Comment by Jiingy** [comment]
This is actually implemented now, just not fully

It does "work" though ![2022-03-19_03 20 21](https://user-images.githubusercontent.com/69827559/159154294-7ca668fb-e15c-40cd-b701-baff395729d6.png)

**Comment by Jiingy** [comment]
Shulker chest implemented, any further issues will be new
