### ISSUE TITLE
Add 'slate' block that generates far underground

### ISSUE THREAD

**Issue by MainGameCentral** [Jiingy/Jineric-Mod#33]
Not as dark as blackstone, but darker than the current overworld stone types.

**Comment by Jiingy** [comment]
Slate was added with WIP texture and generates naturally underground, still needs further implementation.

**Comment by Jiingy** [comment]
Ironically, after neglecting JinericMod for a bit, Mojang released deep'slate'.

Seeing as we intended to basically implement slate as deepslate, I think the idea of 'slate' is dead. Can possibly change the stone to a new type.
