### ISSUE TITLE
Food/Salt

### ISSUE THREAD

**Issue by Stereo528** [Jiingy/Jineric-Mod#35]
Add Baked Golden Potato, Able to salt said potato, improves food gain but reduces saturation
Could also salt vanilla cooked meats/foods for same effect
Also: Add an item like a skillet and can cook food items, requires furnace to craft, if used with salt and item auto salts it, possibly add tiny coal that would be used in the recipe also to make it more realistic for heating, 1 coal turns into 8 tiny coal (same with charcoal)

**Comment by Jiingy** [comment]
We could maybe do this

**Comment by Jiingy** [comment]
salt and salt block was added but it's still useless
