### ISSUE TITLE
Add more painting designs

### ISSUE THREAD

**Issue by heefo** [Jiingy/Jineric-Mod#36]
more!!!
![3x (5)](https://user-images.githubusercontent.com/78193596/106372825-7fdd8e00-6328-11eb-9273-f04e2f7bbfbf.png)

**Comment by Jiingy** [comment]
Added Adam's painting, and two other deltarune themed ones.
![2022-04-13_01 01 12](https://user-images.githubusercontent.com/69827559/163781319-40b94ecc-827d-4570-b6b2-e90b13423af3.png)

**Comment by Jiingy** [comment]
Issue is too vague, closing
