### ISSUE TITLE
Jingy check twitter lol

### ISSUE THREAD

**Issue by MainGameCentral** [Jiingy/Jineric-Mod#41]
This is an SOS please disregard if you are not jingy

**Comment by Jiingy** [comment]
??????

**Comment by Jiingy** [comment]
What am I supposed to check exactly? And why did you post this here?

**Comment by Deviouslrd** [comment]
I am totally jingy
I am checking twitter right this second.

Please stand by...

**Comment by MainGameCentral** [comment]
> What am I supposed to check exactly? And why did you post this here?

I need you to check your dms this was the only way for me to contact you
