### ISSUE TITLE
Add marble block and block varients

### ISSUE THREAD

**Issue by MainGameCentral** [Jiingy/Jineric-Mod#46]
We need a slick white block that isn't quartz, and my first thought is marble.

**Comment by Jiingy** [comment]
I like this idea, but it's another one that might need to be held off for 1.17.

**Comment by Jiingy** [comment]
Calcite has been added in 1.17/.18, and will be recieving more varients by me, but marble is still possible to add.

**Comment by Jiingy** [comment]
Closing in favor of Trello note
