### ISSUE TITLE
Finish adding redsandstone variants 

### ISSUE THREAD

**Issue by MrCheeze446** [Jiingy/Jineric-Mod#53]
wavy:
- [x] w
- [x] st
- [x] sl

chiseled:
- [x] w
- [x] st
- [x] sl

**Comment by Jiingy** [comment]
All recipes now have crafting bench and stone cutter recipes for their own respective blocks.
What's left now is to add "duplicate" recipes to also allow them to be crafted with red sandstone. (just like vanilla sandstone)

**Comment by Jiingy** [comment]
All loot tables have also been added to every red sandstone block. Red sandstone variants are almost entirely implemented

**Comment by Jiingy** [comment]
done
