### ISSUE TITLE
Useless Pickaxe

### ISSUE THREAD

**Issue by CraftyShark99** [Jiingy/Jineric-Mod#91]
For whatever reason, loading the game with this mod causes pickaxes to become completely useless even for vanilla blocks. I have Jade installed for the same modpack and the tooltip does not show Stone as being mineable when it usually shows a wooden pickaxe is required to mine it. Until this issue gets fixed I'll disable this mod from my Curseforge modpack.

**Comment by Jiingy** [comment]
Will investigate this and see what's up with it 👍

**Comment by Jiingy** [comment]
Does this occur with the mod installed by itself outside of a modpack?

**Comment by Jiingy** [comment]
Issue is fixed in version b5.0.1-1.19.4, please update
https://modrinth.com/mod/jineric-mod/version/nNmq2Lrg
